### ISSUE TITLE
refactor project_builder

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#135]
separate `build` method into 2:
- [ ] `build_srpm(spec_file, tarball, srpm_output_dir)` - all params are Pathlib objects, rpmbuild call
- [ ] `build_rpm(srpm_path, distro, arch)` - TODO mock call, add just method definition + existing code

use Command class helper

**Comment by regeciovad** [comment]
Just for sure - build in package_builder?
And I don't understand the things about command class helper. Am I supposed to create new class? 
I would be grateful for more information.

**Comment by jsilhan** [comment]
yes, in package_builder.
```python
output = Command("rpmbuild ...").execute()
# ...
```

**Comment by jsilhan** [comment]
The test should be like:
(you could create spec file manualy but testing RPG spec API is preffered)

```python
def test_build_srpm(self):
    base = Base()
    self.project_name = ...
    self.base_dir = ...
    base.spec.Name = ...
    ...
    base.write_spec()
    base.build_srpm(base.spec_path, TARBALL_PATH, SRPM_OUTPUT_PATH)
    self.assertTrue(SRPM_OUTPUT_PATH.exists())

def TearDown():
    # TODO delete tmp dir
```

More clear? The `spec.load()` is not needed for this task and will not be implemented soon.

**Comment by cibo94** [comment]
I think we have bug here - Travis build log:

```python
test 1
      Start  1: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_spec.py
1: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_spec.py" "-w" "/builddir/build/BUILD/rpg-git-41.1cccfeb"
1: Test timeout computed to be: 9.99988e+06
1: ..
1: ----------------------------------------------------------------------
1: Ran 2 tests in 0.003s
1: 
1: OK
 1/10 Test  #1: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_spec.py ............   Passed    0.36 sec
test 2
      Start  2: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_source_loader.py
2: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_source_loader.py" "-w" "/builddir/build/BUILD/rpg-git-41.1cccfeb"
2: Test timeout computed to be: 9.99988e+06
2: ..../usr/lib64/python3.4/unittest/case.py:563: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
2:   RuntimeWarning)
2: .......
2: ----------------------------------------------------------------------
2: Ran 11 tests in 0.366s
2: 
2: OK
 2/10 Test  #2: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_source_loader.py ...   Passed    0.72 sec
test 3
      Start  3: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_plugins.py
3: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_plugins.py" "-w" "/builddir/build/BUILD/rpg-git-41.1cccfeb"
3: Test timeout computed to be: 9.99988e+06
3: ........
3: ----------------------------------------------------------------------
3: Ran 8 tests in 0.062s
3: 
3: OK
 3/10 Test  #3: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_plugins.py .........   Passed    0.46 sec
test 4
      Start  4: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_plugin_engine.py
4: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_plugin_engine.py" "-w" "/builddir/build/BUILD/rpg-git-41.1cccfeb"
4: Test timeout computed to be: 9.99988e+06
4: ....
4: ----------------------------------------------------------------------
4: Ran 4 tests in 0.007s
4: 
4: OK
 4/10 Test  #4: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_plugin_engine.py ...   Passed    0.39 sec
test 5
      Start  5: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_guess.py
5: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_guess.py" "-w" "/builddir/build/BUILD/rpg-git-41.1cccfeb"
5: Test timeout computed to be: 9.99988e+06
5: ..
5: ----------------------------------------------------------------------
5: Ran 2 tests in 0.002s
5: 
5: OK
 5/10 Test  #5: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_guess.py ...........   Passed    0.36 sec
test 6
      Start  6: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_functional.py
6: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_functional.py" "-w" "/builddir/build/BUILD/rpg-git-41.1cccfeb"
6: Test timeout computed to be: 9.99988e+06
6: E
6: ======================================================================
6: ERROR: test_c_project (test_functional.FunctionalTest)
6: ----------------------------------------------------------------------
6: Traceback (most recent call last):
6:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_functional.py", line 54, in test_c_project
6:     base.build_srpm()
6:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/__init__.py", line 177, in build_srpm
6:     self.spec_path, self.archive_path, self.base_dir)
6:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/package_builder.py", line 29, in build_srpm
6:     .execute()
6:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/command.py", line 46, in execute
6:     return cmd_output(command_lines, binary)
6:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/command.py", line 63, in cmd_output
6:     " 2>/dev/null" ])
6:   File "/usr/lib64/python3.4/subprocess.py", line 620, in check_output
6:     raise CalledProcessError(retcode, process.args, output=output)
6: nose.proxy.CalledProcessError: Command '['/bin/sh', '-c', 'cp /tmp/rpg-hello-1.4.tar.gz-c2ea14b/hello-1.4.tar.gz /builddir/rpmbuild/SOURCES 2>/dev/null']' returned non-zero exit status 1
6: -------------------- >> begin captured logging << --------------------
6: root: INFO: plugin MakePlugin loaded (rpg.plugins.project_builder.make)
6: root: INFO: plugin CMakePlugin loaded (rpg.plugins.project_builder.cmake)
6: root: INFO: plugin FindTranslationPlugin loaded (rpg.plugins.misc.find_translation)
6: root: INFO: plugin FindPatchPlugin loaded (rpg.plugins.misc.find_patch)
6: root: INFO: plugin FindLibraryPlugin loaded (rpg.plugins.misc.find_library)
6: root: INFO: plugin FindFilePlugin loaded (rpg.plugins.misc.find_file)
6: root: INFO: plugin FilesToPkgsPlugin loaded (rpg.plugins.misc.files_to_pkgs)
6: root: INFO: plugin PythonPlugin loaded (rpg.plugins.lang.python)
6: root: INFO: plugin CPlugin loaded (rpg.plugins.lang.c)
6: root: DEBUG: load_sources(tests/project/hello_project/hello-1.4.tar.gz, /tmp/rpg-hello-1.4.tar.gz-c2ea14b/extracted) called
6: root: INFO: plugin phase extracted executed
6: root: INFO: executing FindPatchPlugin plugin
6: root: INFO: plugin phase patched executed
6: root: INFO: executing CMakePlugin plugin
6: root: INFO: executing MakePlugin plugin
6: root: DEBUG: Makefile found
6: root: INFO: executing PythonPlugin plugin
6: root: INFO: executing CPlugin plugin
6: root: INFO: plugin phase installed executed
6: root: INFO: executing FindFilePlugin plugin
6: root: INFO: executing FindTranslationPlugin plugin
6: root: INFO: executing FindLibraryPlugin plugin
6: root: INFO: executing FilesToPkgsPlugin plugin
6: root: WARNING: error during executing plugin FilesToPkgsPlugin:
6:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/plugins/misc/files_to_pkgs.py", line 21, in installed
6:     _query = sack.query().available()
6: 
6: root: DEBUG: build(PosixPath('/tmp/rpg-hello-1.4.tar.gz-c2ea14b/extracted'), PosixPath('/tmp/rpg-hello-1.4.tar.gz-c2ea14b/compiled'), Command('make'))
6: root: INFO: plugin phase compiled executed
6: root: DEBUG: install(PosixPath('/tmp/rpg-hello-1.4.tar.gz-c2ea14b/compiled'), PosixPath('/tmp/rpg-hello-1.4.tar.gz-c2ea14b/installed'), Command('make install DESTDIR=$RPM_BUILD_ROOT'))
6: root: INFO: plugin phase installed executed
6: root: INFO: executing FindFilePlugin plugin
6: root: INFO: executing FindTranslationPlugin plugin
6: root: INFO: executing FindLibraryPlugin plugin
6: root: INFO: executing FilesToPkgsPlugin plugin
6: root: WARNING: error during executing plugin FilesToPkgsPlugin:
6:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/plugins/misc/files_to_pkgs.py", line 21, in installed
6:     _query = sack.query().available()
6: 
6: root: DEBUG: tar zcf /tmp/rpg-hello-1.4.tar.gz-c2ea14b/hello-1.4.tar.gz -C /tmp/rpg-hello-1.4.tar.gz-c2ea14b/extracted . --transform='s/^\./hello-1.4/g'
6: --------------------- >> end captured logging << ---------------------
6: 
6: ----------------------------------------------------------------------
6: Ran 1 test in 0.222s
6: 
6: FAILED (errors=1)
 6/10 Test  #6: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_functional.py ......***Failed    0.56 sec
test 7
      Start  7: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_conf.py
7: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_conf.py" "-w" "/builddir/build/BUILD/rpg-git-41.1cccfeb"
7: Test timeout computed to be: 9.99988e+06
7: ...
7: ----------------------------------------------------------------------
7: Ran 3 tests in 0.004s
7: 
7: OK
 7/10 Test  #7: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_conf.py ............   Passed    0.37 sec
test 8
      Start  8: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_command.py
8: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_command.py" "-w" "/builddir/build/BUILD/rpg-git-41.1cccfeb"
8: Test timeout computed to be: 9.99988e+06
8: ....
8: ----------------------------------------------------------------------
8: Ran 4 tests in 0.019s
8: 
8: OK
 8/10 Test  #8: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_command.py .........   Passed    0.36 sec
test 9
      Start  9: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_build_srpm.py
9: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_build_srpm.py" "-w" "/builddir/build/BUILD/rpg-git-41.1cccfeb"
9: Test timeout computed to be: 9.99988e+06
9: EE
9: ======================================================================
9: ERROR: test_build_srpm (test_build_srpm.BuildSrpmTest)
9: ----------------------------------------------------------------------
9: Traceback (most recent call last):
9:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_build_srpm.py", line 36, in test_build_srpm
9:     self.fbase.build_srpm()
9:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/__init__.py", line 177, in build_srpm
9:     self.spec_path, self.archive_path, self.base_dir)
9:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/package_builder.py", line 29, in build_srpm
9:     .execute()
9:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/command.py", line 46, in execute
9:     return cmd_output(command_lines, binary)
9:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/command.py", line 63, in cmd_output
9:     " 2>/dev/null" ])
9:   File "/usr/lib64/python3.4/subprocess.py", line 620, in check_output
9:     raise CalledProcessError(retcode, process.args, output=output)
9: subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'cp tests/project/hello_project/hello-1.4.tar.gz /builddir/rpmbuild/SOURCES 2>/dev/null']' returned non-zero exit status 1
9: 
9: ======================================================================
9: ERROR: test_build_srpm (test_build_srpm.BuildSrpmTest)
9: ----------------------------------------------------------------------
9: Traceback (most recent call last):
9:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/__init__.py", line 114, in srpm_path
9:     return next(self.base_dir.glob(self.project_name + "*src.rpm"))
9: StopIteration
9: 
9: During handling of the above exception, another exception occurred:
9: 
9: Traceback (most recent call last):
9:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_build_srpm.py", line 40, in tearDown
9:     os.remove(str(self.fbase.srpm_path))
9:   File "/builddir/build/BUILD/rpg-git-41.1cccfeb/rpg/__init__.py", line 118, in srpm_path
9:     .format(str(self.base_dir / (self.project_name + "*src.rpm"))))
9: RuntimeError: Can't find 'tests/project/hello_project/hello*src.rpm'! You need to call build_srpm first.
9: 
9: ----------------------------------------------------------------------
9: Ran 1 test in 0.077s
9: 
9: FAILED (errors=2)
 9/10 Test  #9: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_build_srpm.py ......***Failed    0.44 sec
test 10
      Start 10: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_base.py
10: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_base.py" "-w" "/builddir/build/BUILD/rpg-git-41.1cccfeb"
10: Test timeout computed to be: 9.99988e+06
10: ..
10: ----------------------------------------------------------------------
10: Ran 2 tests in 0.034s
10: 
10: OK
10/10 Test #10: /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_base.py ............   Passed    0.44 sec
80% tests passed, 2 tests failed out of 10
Total Test time (real) =   4.46 sec
The following tests FAILED:
	  6 - /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_functional.py (Failed)
	  9 - /builddir/build/BUILD/rpg-git-41.1cccfeb/tests/test_build_srpm.py (Failed)
```

**Comment by jsilhan** [comment]
`~` seems to be wrongly expanded to `/builddir/`

**Comment by regeciovad** [comment]
The actual version (after cibo94's commit: Home path is now absolute (#172)) has home variable, not "~". But I think this is ok. The problem is "/build/" part. It expects "/builddir/rpmbuild/SOURCES", but we have only "/builddir/build/SOURCES".

**Comment by jsilhan** [comment]
@cibo94 and @regeciovad , can you investigate the cause of the issue by experimenting, making PRs and having them executed by travis?

**Comment by regeciovad** [comment]
I was experimenting and now tests pass. https://github.com/rh-lab-q/rpg/pull/180
How I thought the "correct" path in Travis is /builddir/build/SOURCES. I don't know why, but rpmdev-setuptree doesn't create /rpmbuild/SOURCES on right space (if it did at all). I was trying find other "home" directory, but I am a little bit lost in Travis.

**Comment by cibo94** [comment]
```rpmdev-setuptree``` should create ```rpmbuild``` directory in home directory and '~' is expanded in ```build_srpm``` function so these path should be same. The question is why ```rpmdev-setuptree``` ain't creating ```rpmbuild``` in home directory.

**Comment by regeciovad** [comment]
Well, that is the same thing I wrote, isn't? The problem is: what is correct home directory? Is it actually set up?

**Comment by jsilhan** [comment]
Travis does that hacks but we would like to see tests passing without changing the buildpath inside RPG to Travis CI rpmbuild path. Can you investigate if we can inject `~/rpmbuild` dir from `--buildroot` rpmbuild switch? The other option is to give the spec and tarball path into rpmbuild command line and don't copy it to SOURCES
