### ISSUE TITLE
Miracle test fail

### ISSUE THREAD

**Issue by cibo94** [rh-lab-q/rpg#223]
I don't know what miracle caused it but I have up to date local branch and ```make test``` passes but this not:

```
± % nosetests-3.4 tests/unit
.....................F......./usr/lib64/python3.4/unittest/case.py:563: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
  RuntimeWarning)
.......F.
======================================================================
FAIL: test_find_files (test_plugins.FindPatchPluginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/onionka/Projects/rpg/tests/unit/test_plugins.py", line 87, in test_find_files
    sorted_files)
AssertionError: Lists differ: [('/__pycache__/', '%exclude', None), ('/hell[1030 chars]one)] != [('/Makefile', None, None), ('/__pycache__/',[969 chars]one)]

First differing element 0:
('/__pycache__/', '%exclude', None)
('/Makefile', None, None)

First list contains 2 additional elements.
First extra element 26:
('/translation/CZ.mo', None, None)

- [('/__pycache__/', '%exclude', None),
-  ('/hello', None, None),
-  ('/Makefile', None, None),
? ^

+ [('/Makefile', None, None),
? ^

   ('/__pycache__/', '%exclude', None),
   ('/archives/__pycache__/', '%exclude', None),
   ('/archives/sample.tar.gz', None, None),
   ('/archives/sample.tar.xz', None, None),
   ('/c/__pycache__/', '%exclude', None),
   ('/c/sourcecode.c', None, None),
   ('/hello_project/__pycache__/', '%exclude', None),
   ('/hello_project/hello-1.4.tar.gz', None, None),
   ('/libs/__pycache__/', '%exclude', None),
   ('/libs/libdynamic.so.1', None, None),
   ('/libs/libstatic.a', None, None),
   ('/patch/0.patch', None, None),
   ('/patch/1.patch', None, None),
   ('/patch/2.patch', None, None),
   ('/patch/__pycache__/', '%exclude', None),
   ('/py/__pycache__/', '%exclude', None),
   ('/py/plugin0.py', None, None),
   ('/py/requires/__pycache__/', '%exclude', None),
   ('/py/requires/sourcecode2.py', None, None),
   ('/py/sourcecode.py', None, None),
   ('/srpm/__pycache__/', '%exclude', None),
   ('/srpm/fail.src.rpm', None, None),
   ('/srpm/test.src.rpm', None, None),
   ('/translation/CZ.mo', None, None),
   ('/translation/__pycache__/', '%exclude', None)]

======================================================================
FAIL: test_spec_assignment (test_spec.SpecTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/onionka/Projects/rpg/tests/unit/test_spec.py", line 35, in test_spec_assignment
    self.assertEqual(expected, str(self.spec))
AssertionError: 'Requ[35 chars]qt5\n%build\ncmake .\nmake\n\n%install\nmake i[27 chars]\n\n' != 'Requ[35 chars]qt5\nBuildRequires:\tmake\n%build\ncmake .\nma[742 chars]\n\n'
  Requires:	python3
  Requires:	python3-qt5
+ BuildRequires:	make
  %build
  cmake .
  make
  
  %install
  make install
  
  %check
  make test
  
+ %files
+ -f %{CZ.mo}.lang
+ %exclude /__pycache__/
+ /hello
+ /Makefile
+ %exclude /__pycache__/
+ %exclude /archives/__pycache__/
+ /archives/sample.tar.gz
+ /archives/sample.tar.xz
+ %exclude /c/__pycache__/
+ /c/sourcecode.c
+ %exclude /hello_project/__pycache__/
+ /hello_project/hello-1.4.tar.gz
+ %exclude /libs/__pycache__/
+ /libs/libdynamic.so.1
+ /libs/libstatic.a
+ /patch/0.patch
+ /patch/1.patch
+ /patch/2.patch
+ %exclude /patch/__pycache__/
+ %exclude /py/__pycache__/
+ /py/plugin0.py
+ %exclude /py/requires/__pycache__/
+ /py/requires/sourcecode2.py
+ /py/sourcecode.py
+ %exclude /srpm/__pycache__/
+ /srpm/fail.src.rpm
+ /srpm/test.src.rpm
+ /translation/CZ.mo
+ %exclude /translation/__pycache__/
+ 


----------------------------------------------------------------------
Ran 38 tests in 0.522s

FAILED (failures=2)

```

**Comment by jsilhan** [comment]
[Miro said](https://github.com/rh-lab-q/rpg/pull/232#issuecomment-126756273) this is fixed by https://github.com/rh-lab-q/rpg/pull/232
