### ISSUE TITLE
Requires are converted to list somewhere

### ISSUE THREAD

**Issue by cibo94** [rh-lab-q/rpg#271]
Somewhere, someone converts Requires or maybe BuildRequires to list.

Here is report:
```
[11:07:24] {/home/onionka/Projects/rpg/rpg/plugins/misc/files_to_pkgs.py:20} INFO - Resolving Requires
Traceback (most recent call last):
  File "/home/onionka/Projects/rpg/rpg/gui/wizard.py", line 754, in buildRpm
    self.base.build_rpm_recover(distro, arch)
  File "/home/onionka/Projects/rpg/rpg/__init__.py", line 216, in build_rpm_recover
    analyse()
  File "/home/onionka/Projects/rpg/rpg/__init__.py", line 212, in analyse
    self.sack)
  File "/home/onionka/Projects/rpg/rpg/plugins/misc/files_to_pkgs.py", line 21, in installed
    spec.Requires.update(
AttributeError: 'list' object has no attribute 'update'
```

**Comment by jsilhan** [comment]
someone find all occurrences of spec.(Build)Requires and fix the issue.
