### ISSUE TITLE
add support for rpm macros in the Command

### ISSUE THREAD

**Issue by ignatenkobrain** [rh-lab-q/rpg#285]
I've used `%py3_build` in %build section in wizard where it asks for `%prepare`, `%build` and `%check` sections. It should work and shouldn't crash.

```
$ rpm --eval %py3_build

CFLAGS="-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic" /usr/bin/python3 setup.py  build --executable="/usr/bin/python3 -s" 

```
```python
[16:28:04] {/home/brain/git/upstream/rpg/rpg/project_builder.py:13} DEBUG - build(PosixPath('/tmp/rpg-appdirs-1.4.0.tar.gz-a23245a/extracted'), PosixPath('/tmp/rpg-appdirs-1.4.0.tar.gz-a23245a/compiled'), Command('%py3_build'))
/bin/sh: line 0: fg: no job control
Traceback (most recent call last):
  File "/home/brain/git/upstream/rpg/rpg/gui/wizard.py", line 395, in validatePage
    self.base.build_project()
  File "/home/brain/git/upstream/rpg/rpg/__init__.py", line 229, in build_project
    self.spec.build)
  File "/home/brain/git/upstream/rpg/rpg/project_builder.py", line 19, in build
    build_command.execute_from(project_target_dir)
  File "/home/brain/git/upstream/rpg/rpg/command.py", line 55, in execute_from
    return cmd_output(command_lines)
  File "/home/brain/git/upstream/rpg/rpg/command.py", line 62, in cmd_output
    output = check_output(["/bin/sh", "-c", " && ".join(cmdlines)])
  File "/usr/lib64/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'cd /tmp/rpg-appdirs-1.4.0.tar.gz-a23245a/compiled && %py3_build']' returned non-zero exit status 1
```

**Comment by jsilhan** [comment]
it should basically replace all words in command line starting with `%` with `rpm --eval <macro>`
