### ISSUE TITLE
SIGABRT when press 'next' btn with subprocess.CalledProcessError

### ISSUE THREAD

**Issue by ignatenkobrain** [rh-lab-q/rpg#288]
Related to #285. If I will press 'next' with `%py3_build` field -- RPG will not just ignore error, it will crash with SIGABRT.
```python
[16:54:48] {/home/brain/git/upstream/rpg/rpg/project_builder.py:13} DEBUG - build(PosixPath('/tmp/rpg-appdirs-1.4.0.tar.gz-a23245a/extracted'), PosixPath('/tmp/rpg-appdirs-1.4.0.tar.gz-a23245a/compiled'), Command('%py3_build'))
/bin/sh: line 0: fg: no job control
Traceback (most recent call last):
  File "/home/brain/git/upstream/rpg/rpg/gui/wizard.py", line 395, in validatePage
    self.base.build_project()
  File "/home/brain/git/upstream/rpg/rpg/__init__.py", line 229, in build_project
    self.spec.build)
  File "/home/brain/git/upstream/rpg/rpg/project_builder.py", line 19, in build
    build_command.execute_from(project_target_dir)
  File "/home/brain/git/upstream/rpg/rpg/command.py", line 55, in execute_from
    return cmd_output(command_lines)
  File "/home/brain/git/upstream/rpg/rpg/command.py", line 62, in cmd_output
    output = check_output(["/bin/sh", "-c", " && ".join(cmdlines)])
  File "/usr/lib64/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'cd /tmp/rpg-appdirs-1.4.0.tar.gz-a23245a/compiled && %py3_build']' returned non-zero exit status 1
[16:54:57] {/home/brain/git/upstream/rpg/rpg/project_builder.py:13} DEBUG - build(PosixPath('/tmp/rpg-appdirs-1.4.0.tar.gz-a23245a/extracted'), PosixPath('/tmp/rpg-appdirs-1.4.0.tar.gz-a23245a/compiled'), Command('%py3_build'))
/bin/sh: line 0: fg: no job control
Traceback (most recent call last):
  File "/home/brain/git/upstream/rpg/rpg/gui/wizard.py", line 395, in validatePage
    self.base.build_project()
  File "/home/brain/git/upstream/rpg/rpg/__init__.py", line 229, in build_project
    self.spec.build)
  File "/home/brain/git/upstream/rpg/rpg/project_builder.py", line 19, in build
    build_command.execute_from(project_target_dir)
  File "/home/brain/git/upstream/rpg/rpg/command.py", line 55, in execute_from
    return cmd_output(command_lines)
  File "/home/brain/git/upstream/rpg/rpg/command.py", line 62, in cmd_output
    output = check_output(["/bin/sh", "-c", " && ".join(cmdlines)])
  File "/usr/lib64/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'cd /tmp/rpg-appdirs-1.4.0.tar.gz-a23245a/compiled && %py3_build']' returned non-zero exit status 1
Aborted (core dumped)
```

**Comment by jsilhan** [comment]
We could catch such exceptions at the wizard, exit and print log.critical
