### ISSUE TITLE
Hard-coded architecture in tests

### ISSUE THREAD

**Issue by cibo94** [rh-lab-q/rpg#296]
Someone hard-coded tests that are searching for files. If we are building for i386, files with x86_64 not exists so test will fail.

```
test 1
      Start  1: /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_functional.py
1: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-0.0.2/tests/unit/test_functional.py" "-w" "/builddir/build/BUILD/rpg-0.0.2"
1: Test timeout computed to be: 9.99988e+06
1: F
1: ======================================================================
1: FAIL: test_c_project (test_functional.FunctionalTest)
1: ----------------------------------------------------------------------
1: Traceback (most recent call last):
1:   File "/builddir/build/BUILD/rpg-0.0.2/tests/unit/test_functional.py", line 48, in test_c_project
1:     set(base.spec.required_files))
1: nose.proxy.AssertionError: Items in the first set but not the second:
1: '/usr/include/gnu/stubs-64.h'
1: '/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/stdarg.h'
1: '/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/stddef.h'
1: Items in the second set but not the first:
1: '/usr/lib/gcc/i686-redhat-linux/5.1.1/include/stdarg.h'
1: '/usr/include/gnu/stubs-32.h'
1: '/usr/lib/gcc/i686-redhat-linux/5.1.1/include/stddef.h'
1: -------------------- >> begin captured logging << --------------------
1: root: INFO: plugin FindFilePlugin loaded (rpg.plugins.misc.find_file)
...
1: root: INFO: executing FindLibraryPlugin plugin
1: --------------------- >> end captured logging << ---------------------
1: 
1: ----------------------------------------------------------------------
1: Ran 1 test in 0.055s
1: 
1: FAILED (failures=1)
 1/12 Test  #1: /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_functional.py ......***Failed    0.38 sec
test 2
...
4: OK
 4/12 Test  #4: /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_command.py .........   Passed    0.35 sec
test 5
      Start  5: /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_build_srpm.py
5: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-0.0.2/tests/unit/test_build_srpm.py" "-w" "/builddir/build/BUILD/rpg-0.0.2"
5: Test timeout computed to be: 9.99988e+06
5: /bin/sh: rpmdev-setuptree: command not found
5: EE
5: ======================================================================
5: ERROR: test_build_srpm (test_build_srpm.BuildSrpmTest)
5: ----------------------------------------------------------------------
5: Traceback (most recent call last):
5:   File "/builddir/build/BUILD/rpg-0.0.2/tests/unit/test_build_srpm.py", line 35, in test_build_srpm
5:     self.fbase.build_srpm()
5:   File "/builddir/build/BUILD/rpg-0.0.2/rpg/__init__.py", line 194, in build_srpm
5:     self.spec_path, self.archive_path, self.base_dir)
5:   File "/builddir/build/BUILD/rpg-0.0.2/rpg/package_builder.py", line 26, in build_srpm
5:     Command("rpmdev-setuptree").execute()
5:   File "/builddir/build/BUILD/rpg-0.0.2/rpg/command.py", line 47, in execute
5:     return cmd_output(command_lines, binary)
5:   File "/builddir/build/BUILD/rpg-0.0.2/rpg/command.py", line 63, in cmd_output
5:     output = check_output(["/bin/sh", "-c", " && ".join(cmdlines)])
5:   File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
5:     raise CalledProcessError(retcode, process.args, output=output)
5: subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'rpmdev-setuptree']' returned non-zero exit status 127
5: 
5: ======================================================================
5: ERROR: test_build_srpm (test_build_srpm.BuildSrpmTest)
5: ----------------------------------------------------------------------
5: Traceback (most recent call last):
5:   File "/builddir/build/BUILD/rpg-0.0.2/rpg/__init__.py", line 114, in srpm_path
5:     return next(self.base_dir.glob(self.project_name + "*.src.rpm"))
5: StopIteration
5: 
5: During handling of the above exception, another exception occurred:
5: 
5: Traceback (most recent call last):
5:   File "/builddir/build/BUILD/rpg-0.0.2/tests/unit/test_build_srpm.py", line 39, in tearDown
5:     os.remove(str(self.fbase.srpm_path))
5:   File "/builddir/build/BUILD/rpg-0.0.2/rpg/__init__.py", line 119, in srpm_path
5:     (self.project_name + "*.src.rpm"))))
5: RuntimeError: Can't find 'tests/project/hello_project/hello*.src.rpm'! You need to call build_srpm first.
5: 
5: ----------------------------------------------------------------------
5: Ran 1 test in 0.007s
5: 
5: FAILED (errors=2)
 5/12 Test  #5: /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_build_srpm.py ......***Failed    0.33 sec
test 6
      Start  6: /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_conf.py
6: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-0.0.2/tests/unit/test_conf.py" "-w" "/builddir/build/BUILD/rpg-0.0.2"
...
7: OK
 7/12 Test  #7: /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_spec.py ............   Passed    0.37 sec
test 8
      Start  8: /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_plugins.py
8: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-0.0.2/tests/unit/test_plugins.py" "-w" "/builddir/build/BUILD/rpg-0.0.2"
8: Test timeout computed to be: 9.99988e+06
8: .F..F......
8: ======================================================================
8: FAIL: test_c (test_plugins.FindPatchPluginTest)
8: ----------------------------------------------------------------------
8: Traceback (most recent call last):
8:   File "/builddir/build/BUILD/rpg-0.0.2/tests/unit/test_plugins.py", line 188, in test_c
8:     self.assertEqual(self.spec.required_files, expected)
8: AssertionError: Items in the first set but not the second:
8: '/usr/lib/gcc/i686-redhat-linux/5.1.1/include/stddef.h'
8: '/usr/include/gnu/stubs-32.h'
8: '/usr/lib/gcc/i686-redhat-linux/5.1.1/include/stdarg.h'
8: Items in the second set but not the first:
8: '/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/stddef.h'
8: '/usr/include/gnu/stubs-64.h'
8: '/usr/lib/gcc/x86_64-redhat-linux/5.1.1/include/stdarg.h'
8: 
8: ======================================================================
8: FAIL: test_find_files (test_plugins.FindPatchPluginTest)
8: ----------------------------------------------------------------------
8: Traceback (most recent call last):
8:   File "/builddir/build/BUILD/rpg-0.0.2/tests/unit/test_plugins.py", line 116, in test_find_files
8:     sorted_files)
8: AssertionError: Lists differ: [('/M[602 chars], ('/hello_project/hello.spec', None, None), ([874 chars]one)] != [('/M[602 chars], ('/libs/__pycache__/', '%exclude', None), ('[831 chars]one)]
8: 
8: First differing element 15:
8: ('/hello_project/hello.spec', None, None)
8: ('/libs/__pycache__/', '%exclude', None)
8: 
8: First list contains 1 additional elements.
8: First extra element 37:
8: ('/translation/__pycache__/', '%exclude', None)
8: 
8: Diff is 1646 characters long. Set self.maxDiff to None to see it.
8: 
8: ----------------------------------------------------------------------
8: Ran 11 tests in 0.062s
8: 
8: FAILED (failures=2)
 8/12 Test  #8: /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_plugins.py .........***Failed    0.38 sec
test 9
      Start  9: /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_mock_req.py
9: Test command: /usr/bin/nosetests-3.4 "/builddir/build/BUILD/rpg-0.0.2/tests/unit/test_mock_req.py" "-w" "/builddir/build/BUILD/rpg-0.0.2"
9: Test timeout computed to be: 9.99988e+06
9: 
9: ----------------------------------------------------------------------
9: Ran 0 tests in 0.000s
...
12: OK
12/12 Test #12: /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_guess.py ...........   Passed    0.37 sec
75% tests passed, 3 tests failed out of 12
Total Test time (real) =   4.31 sec
The following tests FAILED:
	  1 - /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_functional.py (Failed)
	  5 - /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_build_srpm.py (Failed)
	  8 - /builddir/build/BUILD/rpg-0.0.2/tests/unit/test_plugins.py (Failed)
Errors while running CTest
```

**Comment by regeciovad** [comment]
I will try to fix these tests.
