### ISSUE TITLE
Hawkey build failed

### ISSUE THREAD

**Issue by cibo94** [rh-lab-q/rpg#319]
```
Processing files: hawkey-0.6.0-1.fc22.i686
error: File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/lib64/libhawkey.so.2
warning: Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/lib64/__pycache__
error: File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/_hawkeymodule.so
warning: Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/include/hawkey/__pycache__
RPM build errors:
warning: Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/lib64/pkgconfig/__pycache__
warning: Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/test/__pycache__
error: File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/__init__.py
warning: Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/share/man/man3/__pycache__
error: File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/test/__init__.py
error: File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/lib64/pkgconfig/hawkey.pc
error: File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/test/_hawkey_testmodule.so
warning: Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/__pycache__
error: File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/lib64/libhawkey.so
    File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/lib64/libhawkey.so.2
    Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/lib64/__pycache__
    File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/_hawkeymodule.so
    Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/include/hawkey/__pycache__
    Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/lib64/pkgconfig/__pycache__
    Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/test/__pycache__
    File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/__init__.py
    Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/share/man/man3/__pycache__
    File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/test/__init__.py
    File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/lib64/pkgconfig/hawkey.pc
    File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/test/_hawkey_testmodule.so
    Directory not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/lib64/python2.7/site-packages/hawkey/__pycache__
    File not found: /builddir/build/BUILDROOT/hawkey-0.6.0-1.fc22.i386/usr/local/lib64/libhawkey.so
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target i686 --nodeps  /builddir/build/SPECS/hawkey.spec 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/util.py", line 493, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target i686 --nodeps  /builddir/build/SPECS/hawkey.spec 
LEAVE do --> EXCEPTION RAISED
```

**Comment by cibo94** [comment]
When I was building it via gui I get this error:
```
Processing files: a-a-a.x86_64
warning: Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/local/include/hawkey/__pycache__
warning: Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/local/lib64/__pycache__
warning: Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/local/share/man/man3/__pycache__
warning: Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/local/lib64/pkgconfig/__pycache__
warning: Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/lib64/python2.7/site-packages/hawkey/test/__pycache__
warning: Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/lib64/python2.7/site-packages/hawkey/__pycache__
Provides: a = a-a a(x86-64) = a-a libhawkey.so.1()(64bit)
Requires(interp): /bin/sh /bin/sh
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires(post): /bin/sh
Requires(postun): /bin/sh
Requires: ld-linux-x86-64.so.2()(64bit) ld-linux-x86-64.so.2(GLIBC_2.3)(64bit) libc.so.6()(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.8)(64bit) libhawkey.so.1()(64bit) libpython2.7.so.1.0()(64bit) libsolv.so.0()(64bit) libsolv.so.0(SOLV_1.0)(64bit) libsolvext.so.0()(64bit) libsolvext.so.0(SOLV_1.0)(64bit) python(abi) = 2.7 rtld(GNU_HASH)
Processing files: a-debuginfo-a-a.x86_64
Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/a-a-a.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/lib64/python2.7/site-packages/hawkey/__init__.pyc
   /usr/lib64/python2.7/site-packages/hawkey/__init__.pyo
   /usr/lib64/python2.7/site-packages/hawkey/test/__init__.pyc
   /usr/lib64/python2.7/site-packages/hawkey/test/__init__.pyo
    Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/local/include/hawkey/__pycache__
    Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/local/lib64/__pycache__
    Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/local/share/man/man3/__pycache__
    Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/local/lib64/pkgconfig/__pycache__
    Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/lib64/python2.7/site-packages/hawkey/test/__pycache__
    Directory not found: /builddir/build/BUILDROOT/a-a-a.x86_64/usr/lib64/python2.7/site-packages/hawkey/__pycache__
    Installed (but unpackaged) file(s) found:
   /usr/lib64/python2.7/site-packages/hawkey/__init__.pyc
   /usr/lib64/python2.7/site-packages/hawkey/__init__.pyo
   /usr/lib64/python2.7/site-packages/hawkey/test/__init__.pyc
   /usr/lib64/python2.7/site-packages/hawkey/test/__init__.pyo
RPM build errors:
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/a.spec 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/util.py", line 493, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/a.spec 
LEAVE do --> EXCEPTION RAISED
```
