### ISSUE TITLE
fix fedora review build issues

### ISSUE THREAD

**Issue by jsilhan** [rh-lab-q/rpg#364]
https://bugzilla.redhat.com/show_bug.cgi?id=1280422
```
Mock Version: 1.2.12
Mock Version: 1.2.12
Mock Version: 1.2.12
ENTER do(['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/rpg.spec'], chrootPath='/var/lib/mock/fedora-rawhide-x86_64/root'shell=FalseprintOutput=Falseenv={'LANG': 'en_US.utf8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'HOME': '/builddir', 'CCACHE_DIR': '/tmp/ccache', 'CCACHE_UMASK': '002'}gid=135user='mockbuild'timeout=0logger=<mockbuild.trace_decorator.getLog object at 0x7f5bae7c3950>uid=1000)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/rpg.spec'] with env {'LANG': 'en_US.utf8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'HOME': '/builddir', 'CCACHE_DIR': '/tmp/ccache', 'CCACHE_UMASK': '002'} and shell False
Building target platforms: x86_64
Building for target x86_64
Wrote: /builddir/build/SRPMS/rpg-0.0.4-1.git.20.4b321ab.fc24.src.rpm
Child return code was: 0
LEAVE do --> 

ENTER do(['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/rpg.spec '], chrootPath='/var/lib/mock/fedora-rawhide-x86_64/root'shell=FalseprintOutput=Falseenv={'LANG': 'en_US.utf8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'HOME': '/builddir', 'CCACHE_DIR': '/tmp/ccache', 'CCACHE_UMASK': '002'}gid=135user='mockbuild'timeout=0logger=<mockbuild.trace_decorator.getLog object at 0x7f5bae7c3950>uid=1000)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/rpg.spec '] with env {'LANG': 'en_US.utf8', 'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'HOME': '/builddir', 'CCACHE_DIR': '/tmp/ccache', 'CCACHE_UMASK': '002'} and shell False
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.PEes2K
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf rpg-git-20.4b321ab
+ /usr/bin/gzip -dc /builddir/build/SOURCES/rpg-git-20.4b321ab.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd rpg-git-20.4b321ab
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.FQXl5n
+ umask 022
+ cd /builddir/build/BUILD
+ cd rpg-git-20.4b321ab
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
+ export CFLAGS
+ CXXFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
+ export CXXFLAGS
+ FFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld'
+ export LDFLAGS
+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON . -DWITH_MAN=1 -DDISABLE_MOCK_TEST=1 -DDISABLE_CONNECTION_TEST=1
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5", minimum required is "3.4") 
-- Python3QT5 exists
-- Makedepend exists
-- File exists
-- CoreUtils exists
-- Rpm developer tools exists
CMake Warning at CMakeLists.txt:70 (MESSAGE):
  Nosetests is missing! - no tests available
-- Installing to dir '/usr/lib/python3.5/site-packages'
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:
    BUILD_SHARED_LIBS
    CMAKE_CXX_FLAGS_RELEASE
    CMAKE_C_FLAGS_RELEASE
    CMAKE_Fortran_FLAGS_RELEASE
    INCLUDE_INSTALL_DIR
    LIB_INSTALL_DIR
    LIB_SUFFIX
    SHARE_INSTALL_PREFIX
    SYSCONF_INSTALL_DIR
-- Build files have been written to: /builddir/build/BUILD/rpg-git-20.4b321ab
+ make doc-man
/usr/bin/cmake -H/builddir/build/BUILD/rpg-git-20.4b321ab -B/builddir/build/BUILD/rpg-git-20.4b321ab --check-build-system CMakeFiles/Makefile.cmake 0
make -f CMakeFiles/Makefile2 doc-man
make[1]: Entering directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
/usr/bin/cmake -H/builddir/build/BUILD/rpg-git-20.4b321ab -B/builddir/build/BUILD/rpg-git-20.4b321ab --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /builddir/build/BUILD/rpg-git-20.4b321ab/CMakeFiles 1
make -f CMakeFiles/Makefile2 doc/CMakeFiles/doc-man.dir/all
make[2]: Entering directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
make -f doc/CMakeFiles/doc-man.dir/build.make doc/CMakeFiles/doc-man.dir/depend
make[3]: Entering directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
cd /builddir/build/BUILD/rpg-git-20.4b321ab && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /builddir/build/BUILD/rpg-git-20.4b321ab /builddir/build/BUILD/rpg-git-20.4b321ab/doc /builddir/build/BUILD/rpg-git-20.4b321ab /builddir/build/BUILD/rpg-git-20.4b321ab/doc /builddir/build/BUILD/rpg-git-20.4b321ab/doc/CMakeFiles/doc-man.dir/DependInfo.cmake --color=
Scanning dependencies of target doc-man
make[3]: Leaving directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
make -f doc/CMakeFiles/doc-man.dir/build.make doc/CMakeFiles/doc-man.dir/build
make[3]: Entering directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
[100%] Building manpage documentation
cd /builddir/build/BUILD/rpg-git-20.4b321ab/doc && PYTHONPATH=/builddir/build/BUILD/rpg-git-20.4b321ab sphinx-build-3 -b man /builddir/build/BUILD/rpg-git-20.4b321ab/doc /builddir/build/BUILD/rpg-git-20.4b321ab/doc
Running Sphinx v1.3.1
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 7 added, 0 changed, 0 removed
reading sources... [ 14%] api_base
reading sources... [ 28%] api_command
reading sources... [ 42%] api_plugin
reading sources... [ 57%] api_spec
reading sources... [ 71%] command_ref
reading sources... [ 85%] index
reading sources... [100%] writing_plugins
looking for now-outdated files... none found
pickling environment... /builddir/build/BUILD/rpg-git-20.4b321ab/doc/api_base.rst:4: WARNING: autodoc: failed to import class 'Base' from module '__init__'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/builddir/build/BUILD/rpg-git-20.4b321ab/rpg/__init__.py", line 12, in <module>
    from rpg.utils import path_to_str
ImportError: No module named 'rpg.utils'
/builddir/build/BUILD/rpg-git-20.4b321ab/doc/api_command.rst:4: WARNING: __all__ should be a list of strings, not <class 'sphinx.ext.autodoc.__all__'> (in module rpg.command) -- ignoring __all__
/builddir/build/BUILD/rpg-git-20.4b321ab/doc/api_plugin.rst:4: WARNING: autodoc: failed to import class 'Plugin' from module 'rpg.plugin'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
ImportError: No module named 'rpg.plugin'
done
checking consistency... done
writing... rpg.8 { } 
build succeeded, 3 warnings.
make[3]: Leaving directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
[100%] Built target doc-man
make[2]: Leaving directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
/usr/bin/cmake -E cmake_progress_start /builddir/build/BUILD/rpg-git-20.4b321ab/CMakeFiles 0
make[1]: Leaving directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.Con6ug
+ umask 022
+ cd /builddir/build/BUILD
+ '[' /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64 '!=' / ']'
+ rm -rf /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64
++ dirname /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64
+ mkdir -p /builddir/build/BUILDROOT
+ mkdir /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64
+ cd rpg-git-20.4b321ab
+ /usr/bin/make install DESTDIR=/builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64
/usr/bin/cmake -H/builddir/build/BUILD/rpg-git-20.4b321ab -B/builddir/build/BUILD/rpg-git-20.4b321ab --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /builddir/build/BUILD/rpg-git-20.4b321ab/CMakeFiles /builddir/build/BUILD/rpg-git-20.4b321ab/CMakeFiles/progress.marks
/usr/bin/make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
/usr/bin/cmake -E cmake_progress_start /builddir/build/BUILD/rpg-git-20.4b321ab/CMakeFiles 0
/usr/bin/make -f CMakeFiles/Makefile2 preinstall
make[1]: Entering directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
make[1]: Nothing to be done for 'preinstall'.
make[1]: Leaving directory '/builddir/build/BUILD/rpg-git-20.4b321ab'
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: ""
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/bin/rpg
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/utils.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/source_loader.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/conf.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/project_builder.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/package_builder.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/command.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugin_engine.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugin.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/spec.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/__init__.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/gui/wizard.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/gui/dialogs.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/lang/python.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/lang/c.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/misc/find_changelog.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/misc/find_file.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/misc/files_to_pkgs.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/misc/find_library.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/misc/find_translation.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/misc/find_patch.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/project_builder/cmake.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/project_builder/autotools.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/project_builder/maven.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/project_builder/setuptools.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/project_builder/make.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5/site-packages/rpg/plugins/recover/bash_command.py
-- Installing: /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/share/man/man8/rpg.8
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /builddir/build/BUILD/rpg-git-20.4b321ab
/usr/lib/rpm/sepdebugcrcfix: Updated 0 CRC32s, 0 CRC32s did match.
find: 'debug': No such file or directory
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Bytecompiling .py files below /builddir/build/BUILDROOT/rpg-0.0.4-1.git.20.4b321ab.fc24.x86_64/usr/lib/python3.5 using /usr/bin/python3.5
+ /usr/lib/rpm/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.obFkPc
+ umask 022
+ cd /builddir/build/BUILD
+ cd rpg-git-20.4b321ab
+ make ARGS=-V test
make: *** No rule to make target 'test'.  Stop.
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.obFkPc (%check)
    Bad exit status from /var/tmp/rpm-tmp.obFkPc (%check)
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/rpg.spec 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 493, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/rpg.spec 
LEAVE do --> EXCEPTION RAISED

Mock Version: 1.2.12
```

**Comment by jsilhan** [comment]
fixed in the https://github.com/rh-lab-q/rpg/commit/1a9aaf884d6c3f638e47f188ce822064cd59d942
