### ISSUE TITLE
Some macros missing in mock

### ISSUE THREAD

**Issue by cibo94** [rh-lab-q/rpg#374]
Mock does not recognize ```%{python3_sitelib}```. This can be caused by different repos used, so the installed dependencies are different(?).

build_log:
```
Mock Version: 1.2.14
ENTER do(['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/RPG.spec'], uid=1000timeout=0env={'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'TERM': 'vt100', 'HOME': '/builddir', 'CCACHE_UMASK': '002', 'CCACHE_DIR': '/tmp/ccache', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'en_US.UTF-8', 'HOSTNAME': 'mock', 'SHELL': '/bin/bash'}chrootPath='/var/lib/mock/fedora-22-x86_64/root'logger=<mockbuild.trace_decorator.getLog object at 0x7f8eaa77a6d8>user='mockbuild'gid=135printOutput=Falseshell=False)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bs --target x86_64 --nodeps /builddir/build/SPECS/RPG.spec'] with env {'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'TERM': 'vt100', 'HOME': '/builddir', 'CCACHE_UMASK': '002', 'CCACHE_DIR': '/tmp/ccache', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'en_US.UTF-8', 'HOSTNAME': 'mock', 'SHELL': '/bin/bash'} and shell False
DEBUG: Unsharing. Flags: 134217728
warning: Could not canonicalize hostname: a05-0730b.kn.vutbr.cz
Building target platforms: x86_64
Building for target x86_64
Wrote: /builddir/build/SRPMS/RPG-NONE-1.fc22.src.rpm
Child return code was: 0
LEAVE do --> 

ENTER do(['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/RPG.spec '], uid=1000timeout=0env={'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'TERM': 'vt100', 'HOME': '/builddir', 'CCACHE_UMASK': '002', 'CCACHE_DIR': '/tmp/ccache', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'en_US.UTF-8', 'HOSTNAME': 'mock', 'SHELL': '/bin/bash'}chrootPath='/var/lib/mock/fedora-22-x86_64/root'logger=<mockbuild.trace_decorator.getLog object at 0x7f8eaa77a6d8>user='mockbuild'gid=135private_network=TrueprintOutput=Falseshell=False)
Executing command: ['bash', '--login', '-c', '/usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/RPG.spec '] with env {'PROMPT_COMMAND': 'printf "\x1b]0;<mock-chroot>\x07<mock-chroot>"', 'TERM': 'vt100', 'HOME': '/builddir', 'CCACHE_UMASK': '002', 'CCACHE_DIR': '/tmp/ccache', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'LANG': 'en_US.UTF-8', 'HOSTNAME': 'mock', 'SHELL': '/bin/bash'} and shell False
DEBUG: Unsharing. Flags: 134217728
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.C7rV3K
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf RPG-NONE
+ /usr/bin/gzip -dc /builddir/build/SOURCES/RPG-NONE.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd RPG-NONE
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.h5qblB
+ umask 022
+ cd /builddir/build/BUILD
+ cd RPG-NONE
+ cmake .
-- Found PythonInterp: /usr/bin/python3.4 (found suitable version "3.4.2", minimum required is "3.4") 
-- Python3QT5 exists
-- Makedepend exists
-- File exists
-- CoreUtils exists
-- Rpm developer tools exists
-- /usr/bin/nosetests-3.4 found
-- Installing to dir '/usr/lib/python3.4/site-packages'
-- Configuring done
-- Generating done
-- Build files have been written to: /builddir/build/BUILD/RPG-NONE
+ /usr/bin/make -j4
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.Lyv34s
+ exit 0
+ umask 022
+ cd /builddir/build/BUILD
+ '[' /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64 '!=' / ']'
+ rm -rf /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64
++ dirname /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64
+ mkdir -p /builddir/build/BUILDROOT
+ mkdir /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64
+ cd RPG-NONE
+ make install DESTDIR=/builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64
Install the project...
-- Install configuration: ""
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/local/bin/rpg
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/source_loader.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugin.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/command.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/conf.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/utils.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/spec.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/project_builder.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugin_engine.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/__init__.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/package_builder.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/gui/wizard.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/gui/dialogs.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/lang/c.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/lang/python.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/misc/find_patch.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/misc/find_changelog.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/misc/find_library.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/misc/find_translation.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/misc/files_to_pkgs.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/misc/find_file.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/project_builder/autotools.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/project_builder/cmake.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/project_builder/make.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/project_builder/setuptools.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/project_builder/maven.py
-- Installing: /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4/site-packages/rpg/plugins/recover/bash_command.py
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /builddir/build/BUILD/RPG-NONE
/usr/lib/rpm/sepdebugcrcfix: Updated 0 CRC32s, 0 CRC32s did match.
find: 'debug': No such file or directory
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Bytecompiling .py files below /builddir/build/BUILDROOT/RPG-NONE-1.fc22.x86_64/usr/lib/python3.4 using /usr/bin/python3.4
+ /usr/lib/rpm/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.YURCom
+ umask 022
+ cd /builddir/build/BUILD
+ cd RPG-NONE
+ make test-unit
Scanning dependencies of target test-unit
................................./usr/lib64/python3.4/unittest/case.py:563: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes
  RuntimeWarning)
...........
----------------------------------------------------------------------
Ran 44 tests in 41.320s
OK
Built target test-unit
+ exit 0
Processing files: RPG-NONE-1.fc22.x86_64
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/files_to_pkgs.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugin_engine.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/lang/c.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/project_builder/maven.py
error: File must begin with "/": %{python3_sitelib}/rpg/package_builder.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/find_translation.py
error: File must begin with "/": %{python3_sitelib}/rpg/utils.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/project_builder/cmake.py
error: File must begin with "/": %{python3_sitelib}/rpg/gui/wizard.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/find_file.py
error: File must begin with "/": %{python3_sitelib}/rpg/command.py
error: File must begin with "/": %{python3_sitelib}/rpg/project_builder.py
error: File must begin with "/": %{python3_sitelib}/rpg/gui/dialogs.py
RPM build errors:
error: File must begin with "/": %{python3_sitelib}/rpg/conf.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/lang/python.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/recover/bash_command.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/project_builder/setuptools.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/project_builder/autotools.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/find_library.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugin.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/project_builder/make.py
error: File must begin with "/": %{python3_sitelib}/rpg/spec.py
error: File must begin with "/": %{python3_sitelib}/rpg/source_loader.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/find_patch.py
error: File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/find_changelog.py
error: File must begin with "/": %{python3_sitelib}/rpg/__init__.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/files_to_pkgs.py
    File must begin with "/": %{python3_sitelib}/rpg/plugin_engine.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/lang/c.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/project_builder/maven.py
    File must begin with "/": %{python3_sitelib}/rpg/package_builder.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/find_translation.py
    File must begin with "/": %{python3_sitelib}/rpg/utils.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/project_builder/cmake.py
    File must begin with "/": %{python3_sitelib}/rpg/gui/wizard.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/find_file.py
    File must begin with "/": %{python3_sitelib}/rpg/command.py
    File must begin with "/": %{python3_sitelib}/rpg/project_builder.py
    File must begin with "/": %{python3_sitelib}/rpg/gui/dialogs.py
    File must begin with "/": %{python3_sitelib}/rpg/conf.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/lang/python.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/recover/bash_command.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/project_builder/setuptools.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/project_builder/autotools.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/find_library.py
    File must begin with "/": %{python3_sitelib}/rpg/plugin.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/project_builder/make.py
    File must begin with "/": %{python3_sitelib}/rpg/spec.py
    File must begin with "/": %{python3_sitelib}/rpg/source_loader.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/find_patch.py
    File must begin with "/": %{python3_sitelib}/rpg/plugins/misc/find_changelog.py
    File must begin with "/": %{python3_sitelib}/rpg/__init__.py
Child return code was: 1
EXCEPTION: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/RPG.spec 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mockbuild/trace_decorator.py", line 84, in trace
    result = func(*args, **kw)
  File "/usr/lib/python3.4/site-packages/mockbuild/util.py", line 526, in do
    raise exception.Error("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
mockbuild.exception.Error: Command failed. See logs for output.
 # bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps  /builddir/build/SPECS/RPG.spec 
LEAVE do --> EXCEPTION RAISED
```

**Comment by cibo94** [comment]
https://ask.fedoraproject.org/en/question/68313/error-file-must-begin-with-python3_sitelib/

**Comment by jsilhan** [comment]
does it work for you locally?

**Comment by cibo94** [comment]
no it does not, the build log is from local mock build - test_build_rpg I think it is called
