### ISSUE TITLE
Hawkey build segfault

### ISSUE THREAD

**Issue by LukasSlouka** [rh-lab-q/rpg#376]
```
 Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Lukas/Documents/Redhat/rpg/rpg/gui/thread.py", line 56, in wrapper
    func(*args)
  File "/home/Lukas/Documents/Redhat/rpg/rpg/__init__.py", line 259, in build_rpm_recover
    build()
  File "/home/Lukas/Documents/Redhat/rpg/rpg/__init__.py", line 249, in build
    self.build_rpm(distro, arch)
  File "/home/Lukas/Documents/Redhat/rpg/rpg/__init__.py", line 241, in build_rpm
    str(self.srpm_path), target_distro, target_arch, self.base_dir)
  File "/home/Lukas/Documents/Redhat/rpg/rpg/package_builder.py", line 105, in build_rpm
    ) + list(self._check_logs(self.temp_dir))
  File "/home/Lukas/Documents/Redhat/rpg/rpg/package_builder.py", line 62, in _check_logs
    with open(str(path / "build.log")) as build_log:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/build.log'
```

**Comment by LukasSlouka** [comment]
```
Traceback (most recent call last):
  File "/home/Lukas/Documents/Redhat/rpg/rpg/__init__.py", line 160, in rpm_path
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Lukas/Documents/Redhat/rpg/rpg/gui/wizard.py", line 1118, in CancelRPM
    if self.base.rpm_path:
  File "/home/Lukas/Documents/Redhat/rpg/rpg/__init__.py", line 165, in rpm_path
    .format(str(self.base_dir / (self.project_name + "*.rpm"))))
RuntimeError: Can't find '/tmp/rpg-556c3c1/hawkey*.rpm'! You need to call build_rpm first.
[17:02:44] {/home/Lukas/Documents/Redhat/rpg/rpg/plugins/misc/files_to_pkgs.py:34} INFO - Resolving Requires
[17:02:44] {/home/Lukas/Documents/Redhat/rpg/rpg/plugins/misc/files_to_pkgs.py:37} INFO - Resolving BuildRequires
QObject::connect: Cannot queue arguments of type 'QTextBlock'
(Make sure 'QTextBlock' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
[17:02:44] {/home/Lukas/Documents/Redhat/rpg/rpg/__init__.py:100} DEBUG - tar zcf /tmp/rpg-556c3c1/hawkey-a.tar.gz -C /tmp/rpg-556c3c1/extracted . --transform='s/^\./hawkey-a/g'
Segmentation fault (core dumped)
```
